### ISSUE TITLE
Cannot find module defineComponent

### ISSUE THREAD

**Issue by StarpTech** [marko-js-samples/marko-fastify#1]
The static files are mounted under `/static` did we miss to configure a prefix ?
```js
$_mod.def("/marko$4.5.2/src/components/registry-browser", function(require, exports, module, __filename, __dirname) { var loadComponent = require('/marko$4.5.2/src/components/loadComponent-dynamic'/*'./loadComponent'*/);
var defineComponent = require('/marko$4.5.2/src/components/defineComponent'/*'./defineComponent'*/);
```

Error
```
index.js:84 Uncaught Error: Cannot find module "/marko$4.5.2/src/components/defineComponent" from "/marko$4.5.2/src/components"
    at moduleNotFoundError (index.js:84)
    at requireModule (index.js:434)
    at instanceRequire (index.js:130)
    at Module.<anonymous> (registry-browser.js:2)
    at Module_prototype.load (index.js:165)
    at requireModule (index.js:466)
    at instanceRequire (index.js:130)
    at Module.<anonymous> (init-components-browser.js:9)
    at Module_prototype.load (index.js:165)
    at requireModule (index.js:466)
```

**Comment by StarpTech** [comment]
The missing file is not always the same. When I refresh the page multiple times a different component is missing.

**Comment by patrick-steele-idem** [comment]
I haven't figured it out yet, but [fastify-static](https://github.com/fastify/fastify-static) middleware seems to be extremely buggy (or the problem is happening somewhere else...). Lasso is writing the correct files to disk, but when the same file gets served up to the browser via the `fastify-static` middleware it has the content for a different file. This is not happening for all files, but a few of the files. Very bizarre.

@austinkelleher I'm guessing this app worked when you pushed the code. Any ideas?

**Comment by StarpTech** [comment]
I replaced fastify with express and it works. Seems really like an issue in `fastify-static`.

**Comment by StarpTech** [comment]
The issue was fixed in a dependency update of fastify. Please reinstall and verify.

**Comment by StarpTech** [comment]
Tested with fastify 0.30.3 and works fine.
